# Generated by Django 5.2.14 on 2026-05-17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("ai_predictions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGeneratedMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_type", models.CharField(choices=[("appointment_reminder", "Appointment Reminder"), ("missed_followup", "Missed Appointment Follow-up"), ("treatment_encouragement", "Treatment Continuation"), ("motivational", "Motivational Reminder"), ("educational", "Educational Tip")], db_index=True, max_length=50)),
                ("language", models.CharField(db_index=True, max_length=10)),
                ("prompt", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("template_key", models.CharField(blank=True, max_length=120)),
                ("provider", models.CharField(default="mock", max_length=50)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("risk_level", models.CharField(blank=True, max_length=20)),
                ("risk_score", models.FloatField(blank=True, null=True)),
                ("delivery_status", models.CharField(choices=[("preview", "Preview"), ("queued", "Queued"), ("sent", "Sent"), ("delivered", "Delivered"), ("failed", "Failed")], db_index=True, default="preview", max_length=20)),
                ("personalization", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_messages", to=settings.AUTH_USER_MODEL)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_messages", to="patients.patient")),
                ("prediction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_messages", to="ai_predictions.aiprediction")),
            ],
            options={
                "db_table": "ai_generated_messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["patient", "created_at"], name="ai_genera_patient_11f37c_idx"),
                    models.Index(fields=["message_type", "created_at"], name="ai_genera_message_b3a7d0_idx"),
                    models.Index(fields=["delivery_status", "created_at"], name="ai_genera_deliver_c2f49c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryTracking",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(choices=[("in_app", "In App"), ("email", "Email"), ("sms", "SMS"), ("whatsapp", "WhatsApp"), ("push", "Push Notification")], default="in_app", max_length=20)),
                ("status", models.CharField(choices=[("preview", "Preview"), ("queued", "Queued"), ("sent", "Sent"), ("delivered", "Delivered"), ("failed", "Failed")], db_index=True, default="queued", max_length=20)),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="ai_interventions.aigeneratedmessage")),
            ],
            options={
                "db_table": "delivery_tracking",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="delivery_t_status__5d2f8d_idx"),
                    models.Index(fields=["channel", "created_at"], name="delivery_t_channel_1bc591_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InterventionLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(choices=[("previewed", "Previewed"), ("generated", "Generated"), ("sent", "Sent"), ("retry", "Retry"), ("status_update", "Status Update")], db_index=True, max_length=40)),
                ("status", models.CharField(choices=[("success", "Success"), ("failed", "Failed")], default="success", max_length=20)),
                ("impact_score", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="intervention_logs", to=settings.AUTH_USER_MODEL)),
                ("message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="logs", to="ai_interventions.aigeneratedmessage")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="intervention_logs", to="patients.patient")),
            ],
            options={
                "db_table": "intervention_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["patient", "created_at"], name="interventi_patient_71d0ff_idx"),
                    models.Index(fields=["action", "created_at"], name="interventi_action__ed3f23_idx"),
                ],
            },
        ),
    ]
