# Generated by Django 5.2.14 on 2026-05-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interventions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aigeneratedmessage',
            new_name='ai_generate_patient_eacc8a_idx',
            old_name='ai_genera_patient_11f37c_idx',
        ),
        migrations.RenameIndex(
            model_name='aigeneratedmessage',
            new_name='ai_generate_message_5b1d85_idx',
            old_name='ai_genera_message_b3a7d0_idx',
        ),
        migrations.RenameIndex(
            model_name='aigeneratedmessage',
            new_name='ai_generate_deliver_16974d_idx',
            old_name='ai_genera_deliver_c2f49c_idx',
        ),
        migrations.RenameIndex(
            model_name='deliverytracking',
            new_name='delivery_tr_status_0a2dc3_idx',
            old_name='delivery_t_status__5d2f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='deliverytracking',
            new_name='delivery_tr_channel_3719d7_idx',
            old_name='delivery_t_channel_1bc591_idx',
        ),
        migrations.RenameIndex(
            model_name='interventionlog',
            new_name='interventio_patient_1c0ed1_idx',
            old_name='interventi_patient_71d0ff_idx',
        ),
        migrations.RenameIndex(
            model_name='interventionlog',
            new_name='interventio_action_fdde61_idx',
            old_name='interventi_action__ed3f23_idx',
        ),
    ]
