# Generated by Django 5.2.14 on 2026-05-16 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('orthodontic', 'Orthodontic'), ('restorative', 'Restorative'), ('preventive', 'Preventive'), ('surgical', 'Surgical'), ('other', 'Other')], default='other', max_length=30)),
                ('duration_weeks', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'treatments',
                'ordering': ['name'],
            },
        ),
    ]
